print(math.floor(3.8))
print(math.ceil(3.2))
print(math.sqrt(81))
print(math.max(4, 9, 2))
print(math.round(3.5))
print(math.clamp(12, 0, 10))

print(string.len("Magnesium"))
print(string.sub("Magnesium", 1, 3))
print(string.find("Magnesium", "nes"))
print(string.upper("mg"))
print(string.contains("Magnesium", "nes"))
print(string.starts_with("Magnesium", "Mag"))
print(string.ends_with("Magnesium", "ium"))
print(string.replace("a-b-a", "a", "x"))
print(string.repeat("ha", 3))
print(string.reverse("abc"))
let ch, ch_err = string.at("abc", 1)
print(ch)
print(ch_err)
let bad_ch, bad_ch_err = string.at("abc", 9)
print(bad_ch)
print(bad_ch_err.kind)

let xs = array.new()
array.push(xs, "a")
array.insert(xs, "b")
array.insert(xs, 1, "z")
print(len(xs))
print(xs[0])
print(array.remove(xs, 2))
print(array.pop(xs))
let first_x, first_x_err = array.get(xs, 0)
print(first_x)
print(first_x_err)
let missing_x, missing_x_err = array.get(xs, 9)
print(missing_x)
print(missing_x_err.kind)
print(array.contains(xs, "z"))
print(array.index_of(xs, "z"))
print(array.first(xs))
print(array.last(xs))
let slice = array.slice(xs, 0, 1)
print(len(slice))
print(slice[0])
let more = ["q"]
array.extend(xs, more)
print(array.last(xs))
array.clear(more)
print(len(more))

let d = dict.new()
dict.set(d, "name", "mg")
print(dict.get(d, "name"))
print(dict.len(d))
print(len(d))
let required_name, required_err = dict.require(d, "name")
print(required_name)
print(required_err)
let missing_name, missing_err = dict.require(d, "missing")
print(missing_name)
print(missing_err.kind)
let copy = dict.clone(d)
print(dict.get(copy, "name"))
dict.merge(copy, &< engine = "fast" >)
print(dict.get(copy, "engine"))
print(dict.has(d, "missing"))
print(dict.delete(d, "name"))
print(dict.has(d, "name"))
dict.clear(copy)
print(dict.len(copy))

let parts = string.split("a,b,c", ",")
print(parts[1])
