let @shared_state = "main"

let handle, err = vm.spawn("tests/fixtures/isolated_child.mg")
print(type(handle))
print(err)
let ok, join_err = vm.join(handle)
print(ok)
print(join_err)
print(vm.status(handle))
print(vm.try_join(handle))
print(@shared_state)

let missing_handle, missing_spawn_err = vm.spawn("tests/fixtures/missing_child.mg")
print(type(missing_handle))
print(missing_spawn_err)
let missing, missing_err = vm.join(missing_handle)
print(missing)
print(missing_err.kind)

let spawned, spawned_err = vm.spawn("tests/fixtures/isolated_child.mg")
print(spawned_err)
let done, done_err = vm.join(spawned)
print(done)
print(done_err)
print(@shared_state)

let infinite, infinite_err = vm.spawn("tests/fixtures/infinite_child.mg")
print(infinite_err)
let timed, timed_err = vm.join(infinite, 1)
print(timed)
print(timed_err.kind)
print(vm.cancel(infinite))
let cancelled, cancelled_err = vm.join(infinite, 1000)
print(cancelled)
print(cancelled_err.kind)
print(vm.status(infinite))
