<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Magnesium</RootNamespace>
    <AssemblyName>Magnesium</AssemblyName>
    <Version>1.1.1</Version>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
