#!/bin/bash

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Use environment variable if set, otherwise default to 5
RUNS=${RUNS:-5}
BENCH_TIMEOUT=${BENCH_TIMEOUT:-30}
BENCH_FILTER=${BENCH:-}
BENCH_DIR="$REPO_ROOT/benchmark"
BENCHMARKS=(
    "fib35"
    "binary_trees"
    "sieve"
    "mandelbrot"
    "dict_bench"
    "arith_loop"
    "call_loop"
    "closure_loop"
    "array_loop"
    "object_fields"
    "gc_alloc"
    "string_concat"
    "control_flow"
    "fallible_lookup"
    "native_len"
    "coroutine_switch"
)

if [ -n "$BENCH_FILTER" ]; then
    FOUND=0
    FILTERED=()
    for BENCH_NAME in "${BENCHMARKS[@]}"; do
        if [ "$BENCH_NAME" = "$BENCH_FILTER" ]; then
            FILTERED=("$BENCH_NAME")
            FOUND=1
            break
        fi
    done
    if [ "$FOUND" -eq 0 ]; then
        echo "Unknown benchmark: $BENCH_FILTER"
        echo "Available benchmarks: ${BENCHMARKS[*]}"
        exit 1
    fi
    BENCHMARKS=("${FILTERED[@]}")
fi

time_command() {
    local runtime="$1"
    local cmd="$2"
    local start end status

    start=$(date +%s%N)
    timeout "$BENCH_TIMEOUT" bash -c "$cmd" > /dev/null
    status=$?
    end=$(date +%s%N)

    if [ "$status" -ne 0 ]; then
        if [ "$status" -eq 124 ]; then
            echo "Benchmark command timed out after ${BENCH_TIMEOUT}s for $runtime: $cmd" >&2
            return 1
        fi
        echo "Benchmark command failed for $runtime: $cmd" >&2
        return 1
    fi

    awk -v start="$start" -v end="$end" 'BEGIN { printf "%.6f", (end - start) / 1000000000 }'
}

echo "=== Phase 0: Cleanup (Generated Bytecode) ==="
for BENCH in "${BENCHMARKS[@]}"; do
    rm -f "$BENCH_DIR/$BENCH.mgc" \
          "$BENCH_DIR/$BENCH.luac" \
          "$BENCH_DIR/$BENCH.luajit"
done
if [ -d "$BENCH_DIR/__pycache__" ]; then
    for BENCH in "${BENCHMARKS[@]}"; do
        rm -f "$BENCH_DIR/__pycache__/$BENCH".cpython-*.pyc
    done
fi
echo "Done."
echo ""

echo "=== Phase 1: Preparation (Full Compilation) ==="
for BENCH in "${BENCHMARKS[@]}"; do
    printf "Building %-15s ... " "$BENCH (all languages)"
    # Magnesium
    $REPO_ROOT/magnesium build $BENCH_DIR/$BENCH.mg > /dev/null || {
        echo "Magnesium build failed."
        exit 1
    }
    # Lua 5.4
    luac -o $BENCH_DIR/$BENCH.luac $BENCH_DIR/$BENCH.lua || {
        echo "Lua build failed."
        exit 1
    }
    # LuaJIT
    luajit -b $BENCH_DIR/$BENCH.lua $BENCH_DIR/$BENCH.luajit || {
        echo "LuaJIT build failed."
        exit 1
    }
    # Python 3
    python3 -m py_compile $BENCH_DIR/$BENCH.py || {
        echo "Python compile failed."
        exit 1
    }
    echo "Done."
done
echo ""

echo "=== Phase 2: Benchmarking ==="

for BENCH in "${BENCHMARKS[@]}"; do
    echo "--------------------------------------------------------"
    echo "Benchmarking: $BENCH"
    echo ""

    # Interpreted / Source Mode
    declare -A INTERP_RUNTIMES=(
        ["Magnesium"]="$REPO_ROOT/magnesium $BENCH_DIR/$BENCH.mg"
        ["Lua 5.4"]="lua $BENCH_DIR/$BENCH.lua"
        ["LuaJIT"]="luajit $BENCH_DIR/$BENCH.lua"
        ["Python 3"]="python3 $BENCH_DIR/$BENCH.py"
    )
    INTERP_ORDER=("Magnesium" "Lua 5.4" "LuaJIT" "Python 3")

    # Bytecode / Compiled Mode
    PY_CACHED=$(find $BENCH_DIR/__pycache__ -name "${BENCH}.cpython-*.pyc" | head -n 1)
    
    declare -A BYTE_RUNTIMES=(
        ["Magnesium (MGC)"]="$REPO_ROOT/magnesium $BENCH_DIR/$BENCH.mgc"
        ["Lua 5.4 (LUAC)"]="lua $BENCH_DIR/$BENCH.luac"
        ["LuaJIT (Byte)"]="luajit $BENCH_DIR/$BENCH.luajit"
        ["Python 3 (PYC)"]="python3 $PY_CACHED"
    )
    BYTE_ORDER=("Magnesium (MGC)" "Lua 5.4 (LUAC)" "LuaJIT (Byte)" "Python 3 (PYC)")

    # 1. Run Interpreted
    echo "### $BENCH - Interpreted / Source Mode ($RUNS runs)"
    printf "| %-16s |" "Runtime"
    for i in $(seq 1 $RUNS); do printf " Run %d |" $i; done
    printf " **Avg** |\n"
    SEP="|------------------|"
    for i in $(seq 1 $RUNS); do SEP="${SEP}-------|"; done
    SEP="${SEP}----------|"
    echo "$SEP"

    for RUNTIME in "${INTERP_ORDER[@]}"; do
        CMD="${INTERP_RUNTIMES[$RUNTIME]}"
        TOTAL=0
        TIMES=""
        for i in $(seq 1 $RUNS); do
            T=$(time_command "$RUNTIME" "$CMD") || exit 1
            TIMES="$TIMES $T"
            TOTAL=$(awk -v t=$TOTAL -v s=$T 'BEGIN {print t + s}')
        done
        AVG=$(awk -v t=$TOTAL -v r=$RUNS 'BEGIN {if (r>0) printf "%.6f", t / r; else print "0.000000"}')
        printf "| %-16s |" "$RUNTIME"
        for TIME_SEC in $TIMES; do printf " %.6fs |" "$TIME_SEC"; done
        printf " **%ss** |\n" "$AVG"
    done
    echo ""

    # 2. Run Compiled
    echo "### $BENCH - Compiled / Bytecode Mode ($RUNS runs)"
    printf "| %-16s |" "Runtime"
    for i in $(seq 1 $RUNS); do printf " Run %d |" $i; done
    printf " **Avg** |\n"
    echo "$SEP"

    for RUNTIME in "${BYTE_ORDER[@]}"; do
        CMD="${BYTE_RUNTIMES[$RUNTIME]}"
        TOTAL=0
        TIMES=""
        for i in $(seq 1 $RUNS); do
            T=$(time_command "$RUNTIME" "$CMD") || exit 1
            TIMES="$TIMES $T"
            TOTAL=$(awk -v t=$TOTAL -v s=$T 'BEGIN {print t + s}')
        done
        AVG=$(awk -v t=$TOTAL -v r=$RUNS 'BEGIN {if (r>0) printf "%.6f", t / r; else print "0.000000"}')
        printf "| %-16s |" "$RUNTIME"
        for TIME_SEC in $TIMES; do printf " %.6fs |" "$TIME_SEC"; done
        printf " **%ss** |\n" "$AVG"
    done
    echo ""
done
